### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by stud777** [Buntaa/BabyGrowthMod#1]
Hi, I try to use this mod v1.0.3 with game v1.1.4 and it doesn't work for other clans' children. I tried to change the order of loading mods and mod's settings.
And all settings fail - children always growhs in several days before 18y.o.

**Comment by Buntaa** [comment]
Answered this on the nexus page.

**Comment by Buntaa** [comment]
![image](https://github.com/Buntaa/BabyGrowthMod/assets/106802950/f11d74aa-8325-48b3-8294-535730a69433)

**Comment by stud777** [comment]
thnks for the mod, it really helps to diversify the game
